name: Despliegue AutomÃ¡tico FTP
on:
  push:
    branches:
      - main  # Se activa cada vez que envÃ­as cambios a la rama principal

jobs:
  web-deploy:
    name: Subiendo archivos al servidor
    runs-on: ubuntu-latest
    steps:
    - name: ðŸšš Obteniendo cÃ³digo de GitHub
      uses: actions/checkout@v3

    - name: ðŸš€ Sincronizando vÃ­a FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: public_html/mistorneos/
        exclude: |
          **/.git*
          **/.github*
          .env